events {}

http {
  server {
    listen 1027;

    location / {
      auth_request /validate;
      auth_request_set $auth_user $upstream_http_x_user;

      proxy_pass http://orion:1026;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header FIWARE-Service agrotic;
    }

    location = /validate {
      internal;
      proxy_pass http://wilma-auth:4000/validate;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_set_header X-Original-Authorization $http_authorization;
    }
  }
}
